### ISSUE TITLE
IRC / discord?

### ISSUE THREAD

**Issue by mdeguzis** [dburm/docker-builder#2]
I have been searching many repositories for a good docker solution in place of OBS / VMs with KVM or solutions like using a chroots. I believe docker to be that next gen solution that works on nearly any distro. I want to atrat deciding a lot of time helping this project instead of  uilding my own solution, as I think you have the right minimal approach to this. 

There's no need to add things that complicate what should be a simple process. I did come across https://github.com/seznam/dbuilder ,but this takes on more of a burden than necessary, hosting images themselves, instead of only doing what is necessary.

Do you have an IRC channel or discord? Would you like one setup? I have confidence in this approach. Jenkins and such is nice and all, but this is a nice minimal approach that does not require much of the end-user. I have been using pbuilder and arch Linux chroots for ages, but I am ready to put some time into a more agnostic approach.

**Comment by mdeguzis** [comment]
Then again,  I wonder how much this differs from just supplying a dockerfile instead of a build script.

**Comment by mdeguzis** [comment]
Looks like OBS night support containers http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.build_containers.html

**Comment by mdeguzis** [comment]
Though this method of yours has many merits since it is easier to debug and follow traditional build techniques of the host OS:

https://specs.openstack.org/openstack/fuel-specs/specs/7.0/replace-obs.html

**Comment by dburm** [comment]
Hi, Michael.

This was part of my previous work on developing distributed CI flow
for our internal project. For now the project is done. I have been
moved into another team, and now I can't keep contributing in the
docker-builer :(
So if you want to use/improve it, then just fork it.

I don't have irc/discord account (as well as a channel).

For about dockerfiles instead on script - yeah, I think, most of
features can be implemented in this way (except `shell` maybe)

OBS: imho this is good tool to build suse packages only. After two
years spent on packaging I think that package should be built by
native tool. Any attempt to make all-purpose tool is doomed to failue.
I didn't look at OBS since v2.4

**Comment by dburm** [comment]
Unfortunaltely fuel is dead :(

2017-07-17 23:45 GMT+04:00 Michael T. DeGuzis <notifications@github.com>:

**Comment by dburm** [comment]
BTW docker-builder uses tmpfs, so it is not good tool to build heavy
packages like ceph.

2017-07-18 0:29 GMT+04:00 Дмитрий Бурмистров <burmistrovda@gmail.com>:

**Comment by mdeguzis** [comment]
I still think there is merit in a docker based tool. I may try to combine some ideas from here and others. The tool can be as minimal as possible and use the distro native tools for the build itself.  I have been building software since 2012.  The idea would be to use the native build tools but just use docker for the build env. Pbuilder isn't far off either. No though! May be a fun experimental project for myself
